package stock.tutility.db.tables;

import java.sql.Connection;

import stock.tutility.db.ConnectionManager;
import stock.tutility.db.DBtype;
import stock.tutility.db.DButil;

public class EodBseDateIndexManager {
	
	private static Connection conn = ConnectionManager.getInstance().getConnection();
	private static final String TABLE_NAME = "tsEodBseDateIndex";

	public static void createTsScripsBseTable(DBtype dbType) {
		
		String sql = "";
		
		switch (dbType) {
		case MYSQL:
			sql = "CREATE TABLE IF NOT EXISTS `" + TABLE_NAME + "` ("+
					"`date` date NOT NULL," +
					"`eodId` int(11) NOT NULL," +
					"UNIQUE KEY `unique` (`eodId`)," +
					"KEY `date` (`date`)" +
					")ENGINE=InnoDB DEFAULT CHARSET=latin1";
			break;
			
		/**
		 * WARNING : Since HSQL doesn't check on itself that if a table exists or not, it falls on
		 * 			the caller to check if the desired table already exists. 
		 * 				Failing to do so will throw an SQL error for duplicate creation. 
		 */
		case HSQLDB:
//			sql = "CREATE TABLE PUBLIC."+TABLE_NAME+ "(" +
//					"ID INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY," +
//					"SCRIPID INTEGER NOT NULL," +
//					"COMPANYNAME VARCHAR(100) NOT NULL," +
//					"BSECODE VARCHAR(20) NOT NULL," +
//					"UNIQUE(SCRIPID,BSECODE)" +
//				")";
			System.out.println("HSQLDB not set for this table as HSQLDB is only to be used to download data!");
			break;	
		default:
			break;
		}		
	
		DButil.createTable(dbType, TABLE_NAME, sql, conn);		
	}

	
}
